packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.4.15
  '@opentelemetry/api': ^1.9.1
  '@opentelemetry/api-logs': ^0.218.0
  '@opentelemetry/core': ^2.7.1
  '@opentelemetry/exporter-logs-otlp-http': ^0.218.0
  '@opentelemetry/exporter-metrics-otlp-http': ^0.218.0
  '@opentelemetry/exporter-trace-otlp-http': ^0.218.0
  '@opentelemetry/instrumentation': ^0.218.0
  '@opentelemetry/instrumentation-http': ^0.218.0
  '@opentelemetry/instrumentation-pino': ^0.64.0
  '@opentelemetry/otlp-exporter-base': ^0.218.0
  '@opentelemetry/resources': ^2.7.1
  '@opentelemetry/sdk-logs': ^0.218.0
  '@opentelemetry/sdk-metrics': ^2.7.1
  '@opentelemetry/sdk-node': ^0.218.0
  '@opentelemetry/sdk-trace-base': ^2.7.1
  '@opentelemetry/semantic-conventions': ^1.41.1
  '@orpc/client': ^1.14.3
  '@orpc/openapi': ^1.14.3
  '@orpc/otel': ^1.14.3
  '@orpc/server': ^1.14.3
  '@orpc/zod': ^1.14.3
  '@t3-oss/env-core': ^0.13.11
  '@t3-oss/env-nextjs': ^0.13.11
  '@tanstack/react-query': ^5.100.10
  '@trigger.dev/sdk': ^4.4.6
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  better-auth: 1.6.11
  dotenv: ^17.4.2
  drizzle-orm: ^0.45.2
  next: ^16.2.6
  react: ^19.2.6
  react-dom: ^19.2.6
  react-email: 5.2.11
  resend: ^6.12.3
  tsdown: ^0.11.0
  typescript: 5.9.3
  zod: ^4.4.3
  '@react-email/components': ^1.0.10
  '@react-email/render': ^2.0.4
  '@react-email/tailwind': ^2.0.6
  '@react-email/preview-server': 5.2.11
