/**
 * Fallback for NEXT_PUBLIC_API_URL when migrating from legacy env vars
 */
function getApiUrlFallback() {
	return (
		process.env.NEXT_PUBLIC_HARMONIA_API_URL ??
		process.env.HARMONIA_BETTER_AUTH_URL ??
		process.env.HARMONIA_CORS_ORIGIN ??
		process.env.NEXT_PUBLIC_HARMONIA_APP_URL
	);
}

/**
 * Server-side runtime env with fallbacks (for api preset, server routes)
 */
export function createServerRuntimeEnv(): NodeJS.ProcessEnv {
	return {
		...process.env,
		NEXT_PUBLIC_HARMONIA_API_URL: getApiUrlFallback(),
		NEXT_PUBLIC_HARMONIA_ALLOWED_ORIGIN:
			process.env.NEXT_PUBLIC_HARMONIA_ALLOWED_ORIGIN ??
			process.env.HARMONIA_CORS_ORIGIN ??
			process.env.HARMONIA_BETTER_AUTH_URL ??
			getApiUrlFallback(),
	};
}

/**
 * Helper to create runtimeEnv object for Next.js presets
 * MUST use literal property access for Next.js bundling to work
 */
export function createNextjsRuntimeEnv() {
	return {
		HARMONIA_DATABASE_URL: process.env.HARMONIA_DATABASE_URL,
		NEXT_PUBLIC_HARMONIA_NODE_ENV: process.env.NEXT_PUBLIC_HARMONIA_NODE_ENV,
		NEXT_PUBLIC_HARMONIA_API_URL: getApiUrlFallback(),
		NEXT_PUBLIC_HARMONIA_ALLOWED_ORIGIN:
			process.env.NEXT_PUBLIC_HARMONIA_ALLOWED_ORIGIN ??
			process.env.HARMONIA_CORS_ORIGIN ??
			process.env.HARMONIA_BETTER_AUTH_URL,
		NEXT_PUBLIC_HARMONIA_WEB_URL:
			process.env.NEXT_PUBLIC_HARMONIA_WEB_URL ??
			process.env.HARMONIA_BETTER_AUTH_URL ??
			process.env.HARMONIA_CORS_ORIGIN,
		NEXT_PUBLIC_HARMONIA_DASHBOARD_URL:
			process.env.NEXT_PUBLIC_HARMONIA_DASHBOARD_URL,
		NEXT_PUBLIC_HARMONIA_EMAIL_PREFERENCES_URL:
			process.env.NEXT_PUBLIC_HARMONIA_EMAIL_PREFERENCES_URL,
		HARMONIA_SPOTIFY_CLIENT_ID: process.env.HARMONIA_SPOTIFY_CLIENT_ID,
		HARMONIA_RESEND_API_KEY: process.env.HARMONIA_RESEND_API_KEY,
		HARMONIA_EMAIL_FROM: process.env.HARMONIA_EMAIL_FROM,
		HARMONIA_EMAIL_REPLY_TO: process.env.HARMONIA_EMAIL_REPLY_TO,
		HARMONIA_RESEND_WEBHOOK_SECRET: process.env.HARMONIA_RESEND_WEBHOOK_SECRET,
		HARMONIA_OTEL_SERVICE_NAME: process.env.HARMONIA_OTEL_SERVICE_NAME,
		HARMONIA_OTEL_SAMPLING_RATE: process.env.HARMONIA_OTEL_SAMPLING_RATE,
		HARMONIA_OTEL_ENABLED: process.env.HARMONIA_OTEL_ENABLED,
		HARMONIA_OTEL_EXPORTER_OTLP_ENDPOINT:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_ENDPOINT,
		HARMONIA_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
		HARMONIA_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT,
		HARMONIA_OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_LOGS_ENDPOINT,
		HARMONIA_OTEL_EXPORTER_OTLP_HEADERS:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_HEADERS,
		HARMONIA_OTEL_EXPORTER_OTLP_PROTOCOL:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_PROTOCOL,
		HARMONIA_OTEL_EXPORTER_OTLP_COMPRESSION:
			process.env.HARMONIA_OTEL_EXPORTER_OTLP_COMPRESSION,
	} as const;
}
